### ISSUE TITLE
Casting Manejadoras

### ISSUE THREAD

**Issue by Javieraeros** [forameuss/NervionPlayers#3]
Cambiar los casting de las clases manejadoras.
La solución está en la clase manejadoraAlumnoDAL
Para las fotos, mirar los listados

**Comment by Javieraeros** [comment]
Porque en caso de que algún valor sea nulo en la bbdd, dará el mismo error. Además, los cambios han de hacerse en las manejadoras

**Comment by migueBarrera** [comment]
vale javi ya estoy con ello , por cierto he estado haciendo algunas pruebas y el Convert.toString(NULL) nos devuelve "" y si es Casting de int es un 0 en lugar de null, eso podria darnos problemas

**Comment by migueBarrera** [comment]
javi ya esta todo cambiado y en principio solucionado solo que hay que tener en cuanta que cuando hay null de int lo pasa a 0 ,  de String a "" y de boolean a false , habria que mirar que ocurre con DateTime.
Por cierto cerramos este Issue o como va esto..
