### ISSUE TITLE
Añadir actualizar a Manejadoras

### ISSUE THREAD

**Issue by Javieraeros** [forameuss/NervionPlayers#5]
En las manejadoras que ponen arriba del todo del fichero //TODO ... hay que añadir el método actualziar

**Comment by adripol94** [comment]
Añadido metodo Actualizar en Manejadora Deporte(https://github.com/forameuss/NervionPlayers/commit/823193c9807ccc9515ce88e1d2a79a2255e11186)
Importante: 

> No depurado, tengo intención de depurarlo mañana

**Comment by adripol94** [comment]
Añadido metodo actualizarEquipo ManejadoraEquipoDAL y cambios en ManejadoraDeporteDAL https://github.com/forameuss/NervionPlayers/commit/16c9a8aac82cb992be29be9a6ae6596f9b5d7f93

**Comment by forameuss** [comment]
Ya están terminados todos los métodos actualizar.
