### ISSUE TITLE
public Alumno getAlumno(String cadena,String password)

### ISSUE THREAD

**Issue by Javieraeros** [forameuss/NervionPlayers#7]
Añadir método que devuelva la información de un alumno al pasarle su correo/alias y su contraseña

**Comment by migueBarrera** [comment]
El metodo está creado pero hay falta la parte en la que comprueba que la contraseña es correcta , Hay que invertigas como verify

**Comment by adripol94** [comment]
Paquete encontrado para facilitar la verificacion del password [CryptoHelper](https://www.nuget.org/packages/CryptoHelper/)

**Comment by adripol94** [comment]
Problema solucionado y Alumno completado en el siguiente Push

Close https://github.com/forameuss/NervionPlayers/commit/986cbec1b49c917f4ded227e06def2fa49e1a056
